MERGE INTO mpa_rating
    VALUES (1, 'G');
MERGE INTO mpa_rating
    VALUES (2, 'PG');
MERGE INTO mpa_rating
    VALUES (3, 'PG-13');
MERGE INTO mpa_rating
    VALUES (4, 'R');
MERGE INTO mpa_rating
    VALUES (5, 'NC-17');
MERGE INTO genres
    VALUES (1, 'Комедия');
MERGE INTO genres
    VALUES (2, 'Драма');
MERGE INTO genres
    VALUES (3, 'Мультфильм');
MERGE INTO genres
    VALUES (4, 'Приключение');
MERGE INTO genres
    VALUES (5, 'Боевик');
MERGE INTO genres
    VALUES (6, 'Вестерн');
MERGE INTO event_types
    VALUES (1, 'LIKE');
MERGE INTO event_types
    VALUES (2, 'FRIEND');
MERGE INTO event_types
    VALUES (3, 'REVIEW');
MERGE INTO event_operations
    VALUES (1, 'ADD');
MERGE INTO event_operations
    VALUES (2, 'UPDATE');
MERGE INTO event_operations
    VALUES (3, 'REMOVE');